training_accuracy = {
    "System reliability (parallel)": 1.0,
    "Complement rule (at least one)": 0.785714,
    "Weibull distribution": 0.5,
    "Quantile from survival function": 0.25,
    "Sum of independent Normals": 0.5,
    "Correlation vs independence": 0.625,
    "Binomial distribution": 0.566667,
    "Variance of Binomial (np(1-p))": 0.5,
    "Marginal density from joint (integration)": 0.5,
    "Uniform distribution on a triangular region": 0.3,
    "Chebyshev inequality": 0.25,
    "Cantelli inequality (one-sided)": 0.166667,
    "Standardization to standard normal (Z-score)": 0.416667,
    "Central Limit Theorem (sum of i.i.d.)": 0.25,
    "Gamma distribution": 0.666667,
    "Small-interval probability via PDF": 0.666667,
    "Size-biased sampling": 0.0,
    "Exponential distribution": 0.633333,
    "Law of total expectation": 0.6,
    "Inclusion–exclusion principle": 0.666667,
    "Poisson distribution": 0.5,
    "Lognormal distribution": 0.833333,
    "Change of variables (univariate)": 0.875,
    "Standard error of the mean (i.i.d.)": 0.0,
    "Hypergeometric distribution": 1.0,
    "Variance of sum using covariance": 0.166667,
    "Covariance from correlation (Cov=ρσXσY)": 0.142857,
    "Conditional probability (multiplication rule)": 0.4375,
    "Hazard rate (f": 0.5,
    "S)": 0.5,
    "Bivariate normal conditional expectation": 0.333333,
    "Geometric probability (uniform disk)": 0.0,
    "Linearity of expectation": 0.2,
    "Geometric distribution": 0.5,
    "Law of total probability": 0.375,
    "Uniform(0": 0.5,
    "1) distribution": 0.5,
    "Order statistics (kth order statistic)": 0.7,
    "Beta distribution": 0.0,
    "Normal distribution": 0.416667,
    "Negative binomial distribution": 0.333333,
    "Bivariate normal quadrant probability": 0.0,
    "Probability from joint density (double integral)": 0.375,
    "Product expectation (independent)": 0.0,
    "Expectation from PDF (integration)": 1.0,
    "Expectation from joint density": 0.0,
    "Order statistics (maximum)": 0.5,
    "Convolution (sum of independent RVs)": 1.0,
    "Chi-square distribution": 0.5,
    "Variance of Poisson (Var=λ)": 0.5,
    "Memoryless property (exponential)": 0.0,
    "Probability from PDF (integration)": 0.0,
    "Discrete uniform distribution": 0.75,
    "PDF validity (nonnegativity": 0.0,
    "normalization)": 0.0,
    "Expectation from PMF (discrete)": 0.0,
    "Rayleigh distribution": 0.5,
    "Half-normal distribution (": 1.0,
    "Z": 1.0,
    ")": 1.0,
    "Indicator variables (I_A I_B = I_{A∩B})": 1.0,
    "Covariance from definition": 0.375,
    "Markov inequality": 1.0,
    "Geometric probability (area ratio)": 0.0,
    "Probability from PMF (sum)": 0.5,
    "Multinomial distribution": 1.0,
    "Survival function properties": 1.0,
    "Continuous uniform on a general interval": 0.5,
    "Joint PDF of independent RVs (product of marginals)": 0.0,
    "Variance of product (independent)": 0.0,
}
